Update testRigor.yml
Validator for empty array

diff --git a/.github/workflows/testRigor.yml b/.github/workflows/testRigor.yml
--- a/.github/workflows/testRigor.yml
+++ b/.github/workflows/testRigor.yml
@@ -37,6 +37,12 @@ jobs:
           for yaml_file in "$yaml_folder"/*.yaml; do
              # Convert YAML to JSON using yq
             json_content=$(yq eval -o=json "$yaml_file")
+
+            # Validate that json_content is not empty and is valid JSON
+            if [ -z "$json_content" ] || ! echo "$json_content" | jq empty; then
+              echo "Invalid or empty JSON content in file: $yaml_file"
+              exit 1
+            fi
           
             # Add json_content to the array in the JSON object using jq
             combined_json=$(jq --argjson content "$json_content" '.baselineMutations += [$content]' <<< "$combined_json")
